// auto generated by go tool dist
// goos=linux goarch=arm


#include "runtime.h"
#include "arch_GOARCH.h"
#include "malloc.h"
#include "stack.h"
void
runtime∕debug·setMaxStack(intgo in, intgo out)
{
#line 11 "/home/pi/go_build/hg/go/src/pkg/runtime/rdebug.goc"

	out = runtime·maxstacksize;
	runtime·maxstacksize = in;
	FLUSH(&out);
}
void
runtime∕debug·setGCPercent(intgo in, intgo out)
{
#line 16 "/home/pi/go_build/hg/go/src/pkg/runtime/rdebug.goc"

	out = runtime·setgcpercent(in);
	FLUSH(&out);
}
void
runtime∕debug·setMaxThreads(intgo in, intgo out)
{
#line 20 "/home/pi/go_build/hg/go/src/pkg/runtime/rdebug.goc"

	out = runtime·setmaxthreads(in);
	FLUSH(&out);
}
void
runtime∕debug·SetPanicOnFault(bool enabled, uint8, uint16, bool old)
{
#line 24 "/home/pi/go_build/hg/go/src/pkg/runtime/rdebug.goc"

	old = g->paniconfault;
	g->paniconfault = enabled;
	FLUSH(&old);
}
